services:
  - type: web
    name: sociallink
    env: node
    startCommand: npm run dev
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_ADMIN_KEY
        sync: false
      - key: SUPABASEDB_URL
        sync: false
