# Exported from Render on 2025-11-22T01:17:56Z
version: "1"
databases:
- name: users-api-disc
  databaseName: users_api_disc
  user: users_api_disc_user
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"
